name: Add issues to project

on:
  workflow_call:
    inputs:
      project-number:
        type: number
        description: Github Project Number
        required: true
    secrets:
      access-token:
        required: true
        description: Github access token.
          
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/orgs/ArroyoDev-LLC/projects/${{ inputs.project-number }}
          github-token: ${{ secrets.access-token }}
